### ISSUE TITLE
Build failed due to ng2-search-filter after lazy loading

### ISSUE THREAD

**Issue by MeghaKumari2203** [solodynamo/ng2-search-filter#30] opened 2018-02-11 08:17 UTC
I am using lazy loading in my app. It was getting build fine when I was not using lazy loading to run my app.
After using ng2-search-filter in one of my lazy loaded module, I am unable to build or prod build my app.
It is looking for index.ts file in ng2-search-filter but there is no such file in the path.
Kindly provide some solution ASAP as I am stucked.

Below is the error message I am getting in the console :

Error: ./node_modules/ng2-search-filter/index.ts
Module build failed: Error: ENOENT: no such file or directory, open '/home/megha/Documents/Meme-Ionic-Projects/meme.care/memecareApp/node_modules/ng2-search-filter/index.js'
    at Error (native)
 @ ./src/pages/healthrecord/healthrecord.module.ts 10:0-56
 @ ./src lazy
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./node_modules/ionic-angular/module.js
 @ ./node_modules/ionic-angular/index.js
 @ ./src/app/app.module.ts
 @ ./src/app/main.ts
    at BuildError.Error (native)
    at new BuildError (/home/megha/Documents/Meme-Ionic-Projects/meme.care/memecareApp/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at callback (/home/megha/Documents/Meme-Ionic-Projects/meme.care/memecareApp/node_modules/@ionic/app-scripts/dist/webpack.js:121:28)
    at emitRecords.err (/home/megha/Documents/Meme-Ionic-Projects/meme.care/memecareApp/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/home/megha/Documents/Meme-Ionic-Projects/meme.care/memecareApp/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/home/megha/Documents/Meme-Ionic-Projects/meme.care/memecareApp/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/home/megha/Documents/Meme-Ionic-Projects/meme.care/memecareApp/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/home/megha/Documents/Meme-Ionic-Projects/meme.care/memecareApp/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/home/megha/Documents/Meme-Ionic-Projects/meme.care/memecareApp/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/home/megha/Documents/Meme-Ionic-Projects/meme.care/memecareApp/node_modules/tapable/lib/Tapable.js:222:13)

**Comment by aVolpe** [comment] 2018-02-11 23:11
You are using the `0.4.1` version?

**Comment by MeghaKumari2203** [comment] 2018-02-12 10:37
Earlier I was using version 0.3.1.
I also tried to build with version 0.4.1 but no success. Please get me some solution.

**Comment by aVolpe** [comment] 2018-02-12 13:47
If you put your module in your main ionic module it works?

**Comment by MeghaKumari2203** [comment] 2018-02-13 04:01
Yes it works and get built too when I am not using lazy loading but not otherwise.

My lazy loaded component has below lines of code : 

import {  Ng2SearchPipeModule } from 'ng2-search-filter';
..
..
 imports: [
    IonicPageModule.forChild(MyPage),
    Ng2SearchPipeModule
  ],
...


myPage.html: 
...
    <div *ngFor="let record of healthrecord |filter:(term != null)?term:undefined"></div>
..
Now, 'filter' is not getting recognized when I am using import in the main module only i.e. app.module.ts.
My current lazy loaded module is importing ng2-search-filter as I have to use filter in current module html to filter some data.

**Comment by aVolpe** [comment] 2018-02-13 23:27
@solodynamo the issue is with how we are deploying to npm, if you deploy the folder 'dist' everything works fine, but you are currently deploying the full root folder, how I can help you fixing this?

**Comment by aVolpe** [comment] 2018-02-13 23:28
@MeghaKumari2203 you can use a `< 0.4.0` version in the meantime

**Comment by solodynamo** [comment] 2018-02-14 02:22
@aVolpe we then need to make `.npmignore` file in the root and then publish package. I will make a PR on this today.

**Comment by solodynamo** [comment] 2018-02-21 12:35
PR was made and merged. If issue still occurs then you may re-open this.

**Closed by solodynamo** 2018-02-21 12:35 UTC
